version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    image: eureka-server-img:0.0.1
    ports:
      - "8761:8761"
    networks:
      - spring_network
    environment:
      - HOSTNAME=localhost
    depends_on:
      - config-server

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: auth-service-img:0.0.1
    ports:
      - "9000:9000"
    networks:
      - spring_network
    depends_on:
      - eureka-server
      - config-server
      - postgres

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: config-server-img:0.0.1
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring_network

  order-service:
    build:
      context: ./orders
      dockerfile: Dockerfile
    image: order-service-img:0.0.1
    ports:
      - "8080:8080"
    networks:
      - spring_network
    depends_on:
      - config-server
      - eureka-server
      - postgres

  payment-service:
    build:
      context: ./payment
      dockerfile: Dockerfile
    image: payment-service-img:0.0.1
    ports:
      - "8081:8081"
    networks:
      - spring_network
    depends_on:
      - eureka-server
      - config-server
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    networks:
      - spring_network
    volumes:
      - ./initial-script.sql:/docker-entrypoint-initdb.d/initial-script.sql
      - postgres-data:/var/lib/postgresql/data

networks:
  spring_network:
    external: true

volumes:
  postgres-data: