spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/herreralemus03/shopping-app-properties.git
          username: herreralemus03
          password: ${GITHUB_TOKEN}
          default-label: master
          encoding: UTF-8

server:
  servlet:
    context-path: /config-server
  port: 8888